Enhancements suggestions
powdahound/s3browser pull request #15
Opened 2017-03-15 15:56 UTC by xakraz

For dev:
* Dockerfile
* docker-compose

Features:
* S3 signed URL support (for private file access)
* Proxified download (if using authentication with the HTTP server)

2019-06-28 10:30 UTC, xakraz commented
@powdahound any thoughts ? If you don't have time, maybe we can just close it :)

2019-07-01 12:42 UTC, powdahound requested changes
Thanks for this. Left a few comments and questions for you

2019-07-01 12:42 UTC, powdahound commented on www/index.php
> +date_default_timezone_set('Europe/Paris');
This would best be moved to a config value to keep it accurate for all users

2019-07-01 12:42 UTC, powdahound commented on www/themes/plain/index.tpl.php
> -    <p>Powered by <a href="http://github.com/powdahound/s3browser/" target="_blank">S3 Browser</a></p>
Let's keep this pointing at the canonical repo :)

2019-07-01 12:42 UTC, powdahound commented on www/include/S3Browser.php
> +          $cur[$part]['signature'] = parse_url(
Does this cause any issues if the object is public?

2019-07-01 12:42 UTC, powdahound commented on README.md
> -Installation on Heroku (preferred)
Why remove the Heroku setup? I know folks have enjoyed the ease of this in the past, though this project doesn't see much usage these days.

2020-03-31 19:41 UTC, powdahound commented
This is pretty ancient now. If anyone wants any of these bits feel free to pull into a new PR.

2020-03-31 19:41 UTC, closed without merging